name = "m10c-iso"
license = "MIT"
licenselink = "https://github.com/Isoheptane/m10c-iso/blob/master/LICENSE.md"
description = "A minimalistic (m10c) theme for bloggers (Modified version)"
homepage = "https://github.com/Isoheptane/m10c-iso"
tags = ["blog", "minimalistic", "minimal", "responsive", "dark"]
features = [
  "minimalistic blog",
  "social icons",
  "editable colors"
]

[author]
  name = "Isoheptane"
  homepage = "https://cascade.moe"
